### ISSUE TITLE
这个运行不了

### ISSUE THREAD

**Issue by yoozeeg** [Sean10/graphicsLearning#1]
你好，我打开这个，出现了问题，主要是编译文件缺少，除了OpenGL-framework之外，还需要什么文件呢

**Comment by Sean10** [comment]
麻烦补充一下系统、编译错误~印象里，如果安装OpenGL一切正常，那就主要看下你的系统环境里，头文件那几项被安装在哪个文件夹下了，可能根据情况需要修改下路径前缀，就像我注释掉的那个那样，linux的话用`find / -name glut.h`等方法检索一下吧。

**Comment by yoozeeg** [comment]
<img width="249" alt="2018-07-10 8 55 49" src="https://user-images.githubusercontent.com/19679260/42483267-1280bcfa-841f-11e8-8d40-18602cb40d4a.png">
这个是错误显示。

**Comment by Sean10** [comment]
@yoozeeg XCode安装完OpenGL，还需要进行一些配置，当时我觉得有些复杂，直接用的terminal执行的。请问，在terminal里，用我给出的clang++来执行。看下这样会不会有错误

**Comment by yoozeeg** [comment]
还是不行emmm
<img width="572" alt="2018-07-11 8 04 14" src="https://user-images.githubusercontent.com/19679260/42543972-0eeb8210-84e1-11e8-9235-60e348b70fac.png">

**Comment by Sean10** [comment]
@yoozeeg https://apple.stackexchange.com/questions/254380/macos-sierra-invalid-active-developer-path 你先安装Xcode Command Line Tools吧……

**Comment by yoozeeg** [comment]
还是不行呀。。。。
<img width="570" alt="2018-07-11 4 06 51" src="https://user-images.githubusercontent.com/19679260/42558646-79bb8b88-8524-11e8-9f5c-2db8c20e7c52.png">

**Comment by yoozeeg** [comment]
<img width="570" alt="2018-07-11 4 06 51" src="https://user-images.githubusercontent.com/19679260/42558677-988fbb10-8524-11e8-8f6e-0106b8865f41.png">
这是错误提示

**Comment by Sean10** [comment]
@yoozeeg :cold_sweat: 你去查一下cd命令，到你下载的代码的目录位置再执行……出现的这些错误，和编译环境没有关系，XCode是ide配置问题，之后的属于linux基本操作命令，可以学习一下……这些问题比较常见，你复制到百度谷歌搜一下就好。

**Comment by yoozeeg** [comment]
啊谢谢！！我终于搞定了！！！不好意思我是个小白！！

**Comment by Sean10** [comment]
@yoozeeg 搞定就好~
